### PR TITLE
PlatformIO support and some improvements

### PR DESCRIPTION
**Pull request by hpsaturn**
## Summary

Hi again. I did some refactors and also I added support for PlatformIO.

## Changes

- [x] Added basic test from old StarmapTest ino into tests directory
- [x] Added PlatformIO project ini file in the root for test it in two architectures for now
- [x] Moved the unnecessary files of the library from src directory*
- [x] Removed the Arduino.h dummy file because it has some compatibility issues
- [x] Also was added a pre-built python script for Pio for some Windows compatibility issues with symlinks

*The CMake files and the main are in examples for now.

**How to run the test:**

Just only download and install PlatformIO core (command line tool), and just perform the checks on the root of the library, with this command:

```cpp
pio run
```
Right now I have issues for ESP32 but, the idea of this PR is advance in this direction to resolve this issues.

## Output

```python
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
Warning! The data size (15285 bytes) is greater than maximum allowed (8192 bytes)
RAM:   [==========]  186.6% (used 15285 bytes from 8192 bytes)
Flash: [=======   ]  66.5% (used 84442 bytes from 126976 bytes)
Building .pio/build/arduino-mega/firmware.hex
================ [SUCCESS] Took 1.03 seconds ======================

Environment    Status    Duration
-------------  --------  ------------
esp32s3        FAILED    00:00:01.599
arduino-mega   SUCCESS   00:00:00.994
==================================================== 1 failed, 1 succeeded in
```

### CODE REVIEW

**Comment by shabaz123** [comment]
Hi,

The code in StarmapMain doesn't build with the changes, that code is intended to speed up development by allowing the code to build on Linux.

I tried these steps (from Linux):

```
cd StarmapMain
mkdir build
cd build
cmake ..
```

That fails, so I tried the following change:
In StarmapMain/CMakeLists.txt file, use the following text:

```
add_executable(${PROJECT_NAME}
    ../../src/Starmap.cpp
    ../../src/arrays.cpp
    main.cpp
)
```

However, the error I now get concerns the missing Arduino.h file. 

```
starmap/src/Starmap.h:7:10: fatal error: Arduino.h: No such file or directory
    7 | #include "Arduino.h"
      |          ^~~~~~~~~~~
compilation terminated.
```

The Linux build needs a stub file to build. I'm wondering if some #ifdef can be used to work around this. Any ideas will help, I'm not sure what to suggest, because I'm still not sure what further structure changes might break that Linux build from working. The Linux build is important, because it saves a huge amount of time testing before uploading to an Arduino.

**Comment by shabaz123** [comment]
Success, I think this is a workable solution, with the following five changes:

(1) As mentioned above, change the lines in examples/StarmapMain/CMakeLists.txt to:

```
add_executable(${PROJECT_NAME}
    ../../src/Starmap.cpp
    ../../src/arrays.cpp
    main.cpp
)
```

(2) In the same file, add the line (at about line number 10 or so):

```
add_definitions(-DLINUX_BUILD=1)
```

(3) in src/Starmap.h, change the line:

```
#include "Arduino.h"
```

to:

```
#ifdef LINUX_BUILD
#include "../examples/StarmapMain/Arduino.h"
#else
#include "Arduino.h"
#endif
```

(4) In the examples/StarmapMain/main.cpp file, change the line:

```
#include "Starmap.h"
```

to:

```
#include "../../src/Starmap.h"
```

(5) Place the stub Arduino.h file into the examples/StarmapMain folder.


If you don't mind adding these changes to your request, I'll get it added. Otherwise I can make the changes immediately after your request is merged. I don't mind either way, but might be cleaner if it's in your request.

**Comment by hpsaturn** [comment]
good. Well, I think that is better merge it this PR for now, and then you will able to apply this solution. What do you think?

**Comment by shabaz123** [comment]
Done, and I've tested that the Linux build successfully works. I've updated the Readme to indicate the new file paths for that.

**Pull request merged**
